import React from "react"
import Head from "next/head"
import { useTranslation } from "next-i18next"

const Header: React.FC = () => {
    const { t } = useTranslation("header")

    return (
        <Head>
            <title>{t("title")}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/public/favicon.ico" />
        </Head>
    )
}

export default Header
