name: Deployment

env:
  NODE_VERSION: 16

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p ./artifacts
      - run: touch log.txt ./artifacts

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Npm install
        run: npm ci

      - name: Tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./artifacts

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        if: failure()
        with:
          name: Artifacts
          path: ./artifacts